name: "HCL AppScan DAST - basic"
on:
  workflow_dispatch
jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run ASoC DAST Scan
        uses: HCL-TECH-SOFTWARE/appscan-dast-action@v1.0.6
        with:
          baseurl:  https://cloud.appscan.com
          asoc_key: ${{secrets.ASOC_KEY}}
          asoc_secret: ${{secrets.ASOC_SECRET}}
          application_id: ${{vars.ASOC_APPID_DAST}}
          dynamic_scan_type: dast
          starting_URL: 'http://192.168.68.227:8088/?mode=demo'
          login_method: userpass
          login_user: admin
          login_password: admin
          network: private
          presence_id: 0a9097ff-aad2-ef11-88cd-00224851d275
          fail_for_noncompliance: false
          wait_for_analysis: true
      - uses: actions/upload-artifact@v4
        name: Upload HCL AppScan HTML Report to Github Artifacts
        with:
          name: AppScan Security Scan HTML Report 
          path: '**/AppScan*.html'
        if: success() || failure()
