- name: HCL AppScan DAST Analyzer
  # You may pin to the exact commit or the version.
  # uses: HCL-TECH-SOFTWARE/appscan-dast-action@081cdab16bded4ba4ec8d73a3fefcec945c65af0
  uses: HCL-TECH-SOFTWARE/appscan-dast-action@v1.0.7
  with:
    # baseURL of ASOC API
    baseurl: # default is https://cloud.appscan.com
    # API key for connecting to ASoC.
    asoc_key: 095db609-bc8e-74e9-e949-5c3a8a6279cb
    # Secret for connecting to ASoC.
    asoc_secret: qrjIZtoymL/jQ9VykamykKUF7F8xvDv5qTvfl0HWm4IM
    # The ASoC application id where your scan will appear.
    application_id: 68917714-0a87-4be0-919a-a40072506be1
    # The name of the scan created in ASoC.
    scan_name: # optional
    # Choose between dast or upload. DAST will require you to specify starting URL and login, while upload will only require you to specify a .scan or .scant file
    dynamic_scan_type: # default is dast
    # If dynamic_scan_type is set to "upload", then you will need to provide the .scan or .scant file here
    scan_or_scant_file: # optional
    # The starting URL of the DAST scan
    starting_URL: # optional, default is https://demo.testfire.net?mode=demo
    # Login Method of the scan, can be none, userpass, or recorded
    login_method: # optional, default is none
    # Optimization level: NoOptimization, Fast, Faster, Fastest
    optimization: # optional, default is Fastest
    # Set the type of network, if this is set to private, you must have AppScan Presence created in advance
    network: # optional, default is public
    # Provide the appscan presence ID here
    presence_id: 5df05d9c-f38f-f011-b485-000d3a033e9c
    # If set to true, this action will deploy a ephemeral (temporary) instance of the AppScan Presence on the runner. Please take note that this will ignore presence_id and network settings, and will force set wait_for_analysis to true
    ephemeral_presence: # optional, default is false
    # if login_method is userpass, provide the username here
    login_user: # optional
    # if login_method is userpass, provide the password here
    login_password: # optional
    # Provide a path to the Login Traffic File data. Supported file type: CONFIG: AppScan Activity Recorder file
    login_sequence_file: # optional
    # Send email notification upon scan completion
    email_notification: # optional, default is false
    # set to personal scan
    personal_scan: # optional, default is false
    # Set this true to wait for analysis to complete before finishing job.
    wait_for_analysis: # default is true
    # maximum duration in minutes before the job will no longer wait and proceeds to complete, default is 360 (6 hours)
    wait_for_analysis_timeout_minutes: # optional, default is 360
    # If **fail_for_noncompliance** = true, fail the job if any non-compliant issues are found in the scan
    fail_for_noncompliance: # optional, default is false
    # If **fail_by_severity** is set to true, failure_threshold must also be set. This will fail the job if any issues equal to or higher (more severe) than failure_threshold are found in the scan.
    fail_by_severity: # optional, default is false
    # If **fail_for_noncompliance** is enabled, the severity that indicates a failure. Lesser severities will not be considered a failure. For example, if failure_threshold is set to Medium, Informational and/or Low severity issues will not cause a failure. Medium, High, and/or Critical issues will cause a failure.	
    failure_threshold: # optional, default is High
